// <auto-generated />
using System;
using DegerliMadenSatis.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DegerliMadenSatis.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240329221714_InitialDb")]
    partial class InitialDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.17");

            modelBuilder.Entity("DegerliMadenSatis.Entity.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDdate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDdate = new DateTime(2024, 3, 30, 1, 17, 14, 545, DateTimeKind.Local).AddTicks(2826),
                            Description = "Altın Kategorisi",
                            IsActive = true,
                            IsDelete = false,
                            ModifiedDate = new DateTime(2024, 3, 30, 1, 17, 14, 545, DateTimeKind.Local).AddTicks(2841),
                            Name = "Nesne Altın",
                            Url = "nesne-altin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDdate = new DateTime(2024, 3, 30, 1, 17, 14, 545, DateTimeKind.Local).AddTicks(2846),
                            Description = "Altın Kategorisi",
                            IsActive = true,
                            IsDelete = false,
                            ModifiedDate = new DateTime(2024, 3, 30, 1, 17, 14, 545, DateTimeKind.Local).AddTicks(2847),
                            Name = "Dijital Altın",
                            Url = "dijital-altin"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDdate = new DateTime(2024, 3, 30, 1, 17, 14, 545, DateTimeKind.Local).AddTicks(2851),
                            Description = "Sarrafiye Kategorisi",
                            IsActive = true,
                            IsDelete = false,
                            ModifiedDate = new DateTime(2024, 3, 30, 1, 17, 14, 545, DateTimeKind.Local).AddTicks(2852),
                            Name = "Sarrafiye",
                            Url = "sarrafiye-altin"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDdate = new DateTime(2024, 3, 30, 1, 17, 14, 545, DateTimeKind.Local).AddTicks(2854),
                            Description = "Gümüş Kategorisi",
                            IsActive = true,
                            IsDelete = false,
                            ModifiedDate = new DateTime(2024, 3, 30, 1, 17, 14, 545, DateTimeKind.Local).AddTicks(2856),
                            Name = "Nesne Gümüş",
                            Url = "nesne-gümüs"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDdate = new DateTime(2024, 3, 30, 1, 17, 14, 545, DateTimeKind.Local).AddTicks(2905),
                            Description = "Gümüş Kategorisi",
                            IsActive = true,
                            IsDelete = false,
                            ModifiedDate = new DateTime(2024, 3, 30, 1, 17, 14, 545, DateTimeKind.Local).AddTicks(2906),
                            Name = "Dijital Gümüş",
                            Url = "dijital-gümüs"
                        });
                });

            modelBuilder.Entity("DegerliMadenSatis.Entity.CategoryProduct", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CategoryId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("CategoryProducts", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            ProductId = 1
                        },
                        new
                        {
                            CategoryId = 2,
                            ProductId = 1
                        },
                        new
                        {
                            CategoryId = 1,
                            ProductId = 2
                        },
                        new
                        {
                            CategoryId = 2,
                            ProductId = 2
                        },
                        new
                        {
                            CategoryId = 1,
                            ProductId = 3
                        },
                        new
                        {
                            CategoryId = 2,
                            ProductId = 3
                        },
                        new
                        {
                            CategoryId = 1,
                            ProductId = 4
                        },
                        new
                        {
                            CategoryId = 2,
                            ProductId = 4
                        },
                        new
                        {
                            CategoryId = 3,
                            ProductId = 5
                        },
                        new
                        {
                            CategoryId = 3,
                            ProductId = 6
                        },
                        new
                        {
                            CategoryId = 3,
                            ProductId = 7
                        },
                        new
                        {
                            CategoryId = 4,
                            ProductId = 8
                        },
                        new
                        {
                            CategoryId = 5,
                            ProductId = 8
                        },
                        new
                        {
                            CategoryId = 4,
                            ProductId = 9
                        },
                        new
                        {
                            CategoryId = 5,
                            ProductId = 9
                        },
                        new
                        {
                            CategoryId = 4,
                            ProductId = 10
                        },
                        new
                        {
                            CategoryId = 5,
                            ProductId = 10
                        });
                });

            modelBuilder.Entity("DegerliMadenSatis.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDdate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHome")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("Properties")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDdate = new DateTime(2024, 3, 30, 1, 17, 14, 545, DateTimeKind.Local).AddTicks(9215),
                            ImageUrl = "1.png",
                            IsActive = true,
                            IsDelete = false,
                            IsHome = false,
                            ModifiedDate = new DateTime(2024, 3, 30, 1, 17, 14, 545, DateTimeKind.Local).AddTicks(9230),
                            Name = "20gr Külçe Altın",
                            Price = 48000m,
                            Properties = "24 Ayar Saflıkta, 20 gr Külçe Altın.",
                            Url = "20gr-külce-altin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDdate = new DateTime(2024, 3, 30, 1, 17, 14, 545, DateTimeKind.Local).AddTicks(9241),
                            ImageUrl = "2.png",
                            IsActive = true,
                            IsDelete = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2024, 3, 30, 1, 17, 14, 545, DateTimeKind.Local).AddTicks(9242),
                            Name = "50gr Külçe Altın",
                            Price = 120000m,
                            Properties = "24 Ayar Saflıkta, 50 gr Külçe Altın.",
                            Url = "50gr-külce-altin"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDdate = new DateTime(2024, 3, 30, 1, 17, 14, 545, DateTimeKind.Local).AddTicks(9246),
                            ImageUrl = "3.png",
                            IsActive = true,
                            IsDelete = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2024, 3, 30, 1, 17, 14, 545, DateTimeKind.Local).AddTicks(9247),
                            Name = "100gr Külçe Altın",
                            Price = 240000m,
                            Properties = "24 Ayar Saflıkta, 100 gr Külçe Altın.",
                            Url = "100gr-külce-altin"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDdate = new DateTime(2024, 3, 30, 1, 17, 14, 545, DateTimeKind.Local).AddTicks(9250),
                            ImageUrl = "4.png",
                            IsActive = true,
                            IsDelete = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2024, 3, 30, 1, 17, 14, 545, DateTimeKind.Local).AddTicks(9251),
                            Name = "250gr Külçe Altın",
                            Price = 620000m,
                            Properties = "24 Ayar Saflıkta, 250 gr Külçe Altın.",
                            Url = "250gr-külce-altin"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDdate = new DateTime(2024, 3, 30, 1, 17, 14, 545, DateTimeKind.Local).AddTicks(9254),
                            ImageUrl = "5.png",
                            IsActive = true,
                            IsDelete = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2024, 3, 30, 1, 17, 14, 545, DateTimeKind.Local).AddTicks(9255),
                            Name = "Çeyrek Altın",
                            Price = 4500m,
                            Properties = "24 Ayar Saflıkta, Çeyrek Altın.",
                            Url = "ceyrek-altin"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDdate = new DateTime(2024, 3, 30, 1, 17, 14, 545, DateTimeKind.Local).AddTicks(9259),
                            ImageUrl = "6.png",
                            IsActive = true,
                            IsDelete = false,
                            IsHome = false,
                            ModifiedDate = new DateTime(2024, 3, 30, 1, 17, 14, 545, DateTimeKind.Local).AddTicks(9260),
                            Name = "Yarım Altın",
                            Price = 90000m,
                            Properties = "24 Ayar Saflıkta, Yarım Altın.",
                            Url = "yarim-altin"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDdate = new DateTime(2024, 3, 30, 1, 17, 14, 545, DateTimeKind.Local).AddTicks(9263),
                            ImageUrl = "7.png",
                            IsActive = true,
                            IsDelete = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2024, 3, 30, 1, 17, 14, 545, DateTimeKind.Local).AddTicks(9264),
                            Name = "Tam Altın",
                            Price = 180000m,
                            Properties = "24 Ayar Saflıkta, Tam Altın.",
                            Url = "tam-altin"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDdate = new DateTime(2024, 3, 30, 1, 17, 14, 545, DateTimeKind.Local).AddTicks(9267),
                            ImageUrl = "8.png",
                            IsActive = true,
                            IsDelete = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2024, 3, 30, 1, 17, 14, 545, DateTimeKind.Local).AddTicks(9268),
                            Name = "100gr Külçe Gümüş",
                            Price = 45000m,
                            Properties = "925 Saflıkta, 100 gr Külçe Gümüş.",
                            Url = "100gr-külce-gümüs"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDdate = new DateTime(2024, 3, 30, 1, 17, 14, 545, DateTimeKind.Local).AddTicks(9271),
                            ImageUrl = "9.png",
                            IsActive = true,
                            IsDelete = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2024, 3, 30, 1, 17, 14, 545, DateTimeKind.Local).AddTicks(9273),
                            Name = "250gr Külçe Gümüş",
                            Price = 112500m,
                            Properties = "925 Saflıkta, 250 gr Külçe Gümüş.",
                            Url = "250gr-külce-gümüs"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDdate = new DateTime(2024, 3, 30, 1, 17, 14, 545, DateTimeKind.Local).AddTicks(9279),
                            ImageUrl = "10.png",
                            IsActive = true,
                            IsDelete = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2024, 3, 30, 1, 17, 14, 545, DateTimeKind.Local).AddTicks(9280),
                            Name = "500gr Külçe Gümüş",
                            Price = 225000m,
                            Properties = "925 Saflıkta, 500 gr Külçe Gümüş.",
                            Url = "500gr-külce-gümüs"
                        });
                });

            modelBuilder.Entity("DegerliMadenSatis.Entity.CategoryProduct", b =>
                {
                    b.HasOne("DegerliMadenSatis.Entity.Category", "Category")
                        .WithMany("CategoryProducts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DegerliMadenSatis.Entity.Product", "Product")
                        .WithMany("CategoryProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DegerliMadenSatis.Entity.Category", b =>
                {
                    b.Navigation("CategoryProducts");
                });

            modelBuilder.Entity("DegerliMadenSatis.Entity.Product", b =>
                {
                    b.Navigation("CategoryProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
