// <auto-generated />
using System;
using DegerliMadenSatis.Data.Concrete.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DegerliMadenSatis.Data.Migrations
{
    [DbContext(typeof(DegerliMadenSatisDbContext))]
    partial class DegerliMadenSatisDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.17");

            modelBuilder.Entity("DegerliMadenSatis.Entity.Concrete.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 3, 31, 3, 21, 50, 567, DateTimeKind.Local).AddTicks(8524),
                            Description = "Altın Kategorisi",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 3, 31, 3, 21, 50, 567, DateTimeKind.Local).AddTicks(8542),
                            Name = "Fiziki Altın",
                            Url = "fiziki-altin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 3, 31, 3, 21, 50, 567, DateTimeKind.Local).AddTicks(8548),
                            Description = "Altın Kategorisi",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 3, 31, 3, 21, 50, 567, DateTimeKind.Local).AddTicks(8549),
                            Name = "Dijital Altın",
                            Url = "dijital-altin"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 3, 31, 3, 21, 50, 567, DateTimeKind.Local).AddTicks(8552),
                            Description = "Ziynet Kategorisi",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 3, 31, 3, 21, 50, 567, DateTimeKind.Local).AddTicks(8553),
                            Name = "Ziynet Altın",
                            Url = "ziynet-altin"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 3, 31, 3, 21, 50, 567, DateTimeKind.Local).AddTicks(8556),
                            Description = "Gümüş Kategorisi",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 3, 31, 3, 21, 50, 567, DateTimeKind.Local).AddTicks(8557),
                            Name = "Fiziki Gümüş",
                            Url = "fiziki-gümüs"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 3, 31, 3, 21, 50, 567, DateTimeKind.Local).AddTicks(8559),
                            Description = "Gümüş Kategorisi",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 3, 31, 3, 21, 50, 567, DateTimeKind.Local).AddTicks(8561),
                            Name = "Dijital Gümüş",
                            Url = "dijital-gümüs"
                        });
                });

            modelBuilder.Entity("DegerliMadenSatis.Entity.Concrete.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("date('now')");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHome")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("date('now')");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("real");

                    b.Property<string>("Properties")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 3, 31, 3, 21, 50, 576, DateTimeKind.Local).AddTicks(3281),
                            ImageUrl = "1.png",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2024, 3, 31, 3, 21, 50, 576, DateTimeKind.Local).AddTicks(3304),
                            Name = "5 Gr Külçe Altın",
                            Price = 13500m,
                            Properties = "24 Ayar 995.0 Saflıkta, 5 Gr Külçe Altın.",
                            Url = "5-gr-külce-altin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 3, 31, 3, 21, 50, 576, DateTimeKind.Local).AddTicks(3315),
                            ImageUrl = "1.png",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2024, 3, 31, 3, 21, 50, 576, DateTimeKind.Local).AddTicks(3317),
                            Name = "10 Gr Külçe Altın",
                            Price = 27000m,
                            Properties = "24 Ayar 995.0 Saflıkta, 10 Gr Külçe Altın.",
                            Url = "10-gr-külce-altin"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 3, 31, 3, 21, 50, 576, DateTimeKind.Local).AddTicks(3321),
                            ImageUrl = "2.png",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = false,
                            ModifiedDate = new DateTime(2024, 3, 31, 3, 21, 50, 576, DateTimeKind.Local).AddTicks(3322),
                            Name = "20 Gr Külçe Altın",
                            Price = 54000m,
                            Properties = "24 Ayar 995.0 Saflıkta, 20 Gr Külçe Altın.",
                            Url = "20-gr-külce-altin"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 3, 31, 3, 21, 50, 576, DateTimeKind.Local).AddTicks(3325),
                            ImageUrl = "3.png",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2024, 3, 31, 3, 21, 50, 576, DateTimeKind.Local).AddTicks(3327),
                            Name = "50 Gr Külçe Altın",
                            Price = 135000m,
                            Properties = "24 Ayar 995.0 Saflıkta, 50 Gr Külçe Altın.",
                            Url = "50-gr-külce-altin"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 3, 31, 3, 21, 50, 576, DateTimeKind.Local).AddTicks(3330),
                            ImageUrl = "4.png",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2024, 3, 31, 3, 21, 50, 576, DateTimeKind.Local).AddTicks(3331),
                            Name = "100 Gr Külçe Altın",
                            Price = 270000m,
                            Properties = "24 Ayar 995.0 Saflıkta, 100 Gr Külçe Altın.",
                            Url = "100-gr-külce-altin"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 3, 31, 3, 21, 50, 576, DateTimeKind.Local).AddTicks(3335),
                            ImageUrl = "5.png",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2024, 3, 31, 3, 21, 50, 576, DateTimeKind.Local).AddTicks(3336),
                            Name = "250 Gr Külçe Altın",
                            Price = 680000m,
                            Properties = "24 Ayar 995.0 Saflıkta, 250 Gr Külçe Altın.",
                            Url = "250-gr-külce-altin"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2024, 3, 31, 3, 21, 50, 576, DateTimeKind.Local).AddTicks(3340),
                            ImageUrl = "6.png",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = false,
                            ModifiedDate = new DateTime(2024, 3, 31, 3, 21, 50, 576, DateTimeKind.Local).AddTicks(3341),
                            Name = "500 Gr Külçe Altın",
                            Price = 1350000m,
                            Properties = "24 Ayar 995.0 Saflıkta, 500 Gr Külçe Altın.",
                            Url = "500-gr-külce-altin"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2024, 3, 31, 3, 21, 50, 576, DateTimeKind.Local).AddTicks(3345),
                            ImageUrl = "7.png",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2024, 3, 31, 3, 21, 50, 576, DateTimeKind.Local).AddTicks(3346),
                            Name = "1000 Gr Külçe Altın",
                            Price = 270000m,
                            Properties = "24 Ayar 995.0 Saflıkta, 500 Gr Külçe Altın.",
                            Url = "1000-gr-külce-altin"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2024, 3, 31, 3, 21, 50, 576, DateTimeKind.Local).AddTicks(3350),
                            ImageUrl = "8.png",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = false,
                            ModifiedDate = new DateTime(2024, 3, 31, 3, 21, 50, 576, DateTimeKind.Local).AddTicks(3351),
                            Name = "Çeyrek Altın",
                            Price = 4700m,
                            Properties = "22 Ayar 916.0 Saflıkta, 1.75 Gr Çeyrek Altın.",
                            Url = "ceyrek-altin"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2024, 3, 31, 3, 21, 50, 576, DateTimeKind.Local).AddTicks(3355),
                            ImageUrl = "9.png",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2024, 3, 31, 3, 21, 50, 576, DateTimeKind.Local).AddTicks(3356),
                            Name = "Yarım",
                            Price = 1250m,
                            Properties = "22 Ayar 916.0 Saflıkta, 3.50 Gr Yarım Altın.",
                            Url = "yarim-altin"
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2024, 3, 31, 3, 21, 50, 576, DateTimeKind.Local).AddTicks(3360),
                            ImageUrl = "10.png",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2024, 3, 31, 3, 21, 50, 576, DateTimeKind.Local).AddTicks(3361),
                            Name = "Tam Altın",
                            Price = 2100m,
                            Properties = "22 Ayar 916.0 Saflıkta, 7 Gr Tam Altın.",
                            Url = "tam-altin"
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2024, 3, 31, 3, 21, 50, 576, DateTimeKind.Local).AddTicks(3364),
                            ImageUrl = "12.png",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2024, 3, 31, 3, 21, 50, 576, DateTimeKind.Local).AddTicks(3365),
                            Name = "100gr Külçe Gümüş",
                            Price = 3500m,
                            Properties = "999.0 Saflıkta, 100 Gr Külçe Gümüş.",
                            Url = "100gr-külce-gümüs"
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2024, 3, 31, 3, 21, 50, 576, DateTimeKind.Local).AddTicks(3368),
                            ImageUrl = "13.png",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2024, 3, 31, 3, 21, 50, 576, DateTimeKind.Local).AddTicks(3369),
                            Name = "250gr Külçe Gümüş",
                            Price = 8000m,
                            Properties = "999.0 Saflıkta, 250 Gr Külçe Gümüş.",
                            Url = "250gr-külce-gümüs"
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2024, 3, 31, 3, 21, 50, 576, DateTimeKind.Local).AddTicks(3377),
                            ImageUrl = "14.png",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2024, 3, 31, 3, 21, 50, 576, DateTimeKind.Local).AddTicks(3379),
                            Name = "500gr Külçe Gümüş",
                            Price = 16000m,
                            Properties = "999.0 Saflıkta, 500 Gr Külçe Gümüş.",
                            Url = "500gr-külce-gümüs"
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2024, 3, 31, 3, 21, 50, 576, DateTimeKind.Local).AddTicks(3382),
                            ImageUrl = "15.png",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2024, 3, 31, 3, 21, 50, 576, DateTimeKind.Local).AddTicks(3383),
                            Name = "250gr Külçe Gümüş",
                            Price = 32000m,
                            Properties = "999.0 Saflıkta, 1000 Gr Külçe Gümüş.",
                            Url = "1000gr-külce-gümüs"
                        });
                });

            modelBuilder.Entity("DegerliMadenSatis.Entity.Concrete.ProductCategory", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductCategories", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 1,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 5
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = 5
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = 5
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryId = 5
                        });
                });

            modelBuilder.Entity("DegerliMadenSatis.Entity.Concrete.ProductCategory", b =>
                {
                    b.HasOne("DegerliMadenSatis.Entity.Concrete.Category", "Category")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DegerliMadenSatis.Entity.Concrete.Product", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DegerliMadenSatis.Entity.Concrete.Category", b =>
                {
                    b.Navigation("ProductCategories");
                });

            modelBuilder.Entity("DegerliMadenSatis.Entity.Concrete.Product", b =>
                {
                    b.Navigation("ProductCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
